# Generated by Django 3.1.3 on 2020-11-23 18:04

import Services.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ชื่อบริษัทขนส่ง')),
                ('price', models.IntegerField(verbose_name='ราคาขนส่ง')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShippingID', models.CharField(default=Services.models.serial_combine, max_length=50, verbose_name='Tracking Number')),
                ('OrderID', models.IntegerField(verbose_name='รหัสสินค้า')),
                ('status', models.CharField(choices=[('O', 'Ordered'), ('R', 'Ready'), ('S', 'Shipped'), ('D', 'Delivered')], default='O', max_length=1, verbose_name='สถานะการจัดส่ง')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Services.carrier', verbose_name='บริษัทขนส่ง')),
            ],
        ),
    ]
