# Generated by Django 3.1.3 on 2020-11-23 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='คำอธิบาย')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('orderItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.orderitem', verbose_name='')),
            ],
        ),
    ]
