# Generated by Django 3.1.3 on 2020-11-23 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_orderdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddField(
            model_name='orderdescription',
            name='status',
            field=models.CharField(choices=[('O', 'Ordered'), ('R', 'Ready'), ('S', 'Shipped'), ('D', 'Delivered')], default='O', max_length=1, verbose_name='สถานะการจัดส่ง'),
        ),
        migrations.AlterField(
            model_name='orderdescription',
            name='orderItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.orderitem', verbose_name='Order Item'),
        ),
        migrations.AlterField(
            model_name='orderdescription',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='เวลา'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='OrderID',
            field=models.IntegerField(verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='เวลา'),
        ),
    ]
