# Generated by Django 3.1.3 on 2020-11-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_auto_20201124_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.CharField(default='', max_length=50, verbose_name='USER ID'),
        ),
    ]
