# Generated by Django 3.1.3 on 2020-11-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_auto_20201124_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='user',
            new_name='seller',
        ),
    ]
