# Generated by Django 3.1.3 on 2020-11-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_auto_20201124_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='seller',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shop_id',
            field=models.CharField(default='', max_length=50, verbose_name='Shop ID'),
        ),
    ]
