# Generated by Django 3.1.3 on 2020-11-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_auto_20201124_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='ShippingID',
            new_name='shippingid',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='OrderID',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderid',
            field=models.CharField(default='', max_length=50, verbose_name='Order ID'),
        ),
    ]
